### PR TITLE
Move modules to profile in scope of FKDK cleanup

### PR DESCRIPTION
**Pull request by andriyun**
In scope of prepraring os2web profile for new project we are going to cleanup sites/all folder and move all common functionality and code to profile

See steps to test it in PR https://github.com/fredericia/web/pull/8

### CODE REVIEW

**Comment by andriyun** [comment]
I will add references and howto test steps a bit later
so we can check it on your/Franz side

**Comment by hjemmesidekongen** [comment]
But we need to test it before merging it into master?

**Comment by andriyun** [comment]
Yes... So don't merge it before we are not sure that it works correctly

**Comment by hjemmesidekongen** [comment]
Works fine for me 👍

**Comment by andriyun** [comment]
@franzskaaning Please check functionality side

**Comment by franzskaaning** [comment]
http://test.fredericia.bellcom.dk/node/add/os2web-base-contentpage

CKeditor is not loading in text fields.

**Comment by franzskaaning** [comment]
Feature modules was moved from profile to sites all to fix incompatibility to Svendborg. By moving them back we will need to work on the Svendborg fork as well. 

svendborg:/var/www/svendborg.dk/public_html/profiles/os2web$ git config --get remote.origin.url
git@github.com:bellcom/os2web_profile.git

**Comment by andriyun** [comment]
@franzskaaning @skifter @hjemmesidekongen 
To don't block work with new project, merging and updating checks, I propose to start use versioning of os2web profile like it uses on Drupal.org: 1.x, 2.x, 3.x
I'm going to rename FKDK-cleanup branch to 2.x and we can start work with new project based on this branch.

All current projects using master branch will stay on master and should be checked out to 1.x branch which should be the same as master until will not be deleted.

To share functionality btw projects on different major branches we will need to backport solutions

We also can upgrade major version of osweb_profile from 1.x to 2.x. as we did for fredericia.dk https://github.com/fredericia/web/pull/8
But we will need to spent some amount of time to upgrade and tests.

**Comment by andriyun** [comment]
Going to close this pull request as unusable based on made decision above ^^^

**Pull request closed without merging**
